name: Apptainer Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update 

    - uses: actions/checkout@v2
    - name: Install common software propertes
      run: sudo apt install -y software-properties-common

    - uses: actions/checkout@v2
    - name: add ppa
      run: sudo add-apt-repository -y ppa:apptainer/ppa

    - uses: actions/checkout@v2
    - name: apt update again
      run: sudo apt update

    - uses: actions/checkout@v2
    - name: Install apptainer
      run: sudo apt install -y apptainer
    
    - uses: actions/checkout@v2
    - name: Build the fdm Apptainer image
      run: sudo apptainer build fdm.sif fdm.def 

    - uses: actions/checkout@v2
    - name: Build the postgres Apptainer image
      run: sudo apptainer build post.sif post.def 
